image: gafsel/java-postgres-build

pipelines:
  tags:
    prod-*:
      - step:
          script:
            - apt-get update
            - apt-get install -y sshpass npm && ln -s /usr/bin/nodejs /usr/bin/node
            - npm install --global bower grunt
            - cd src/main/webapp && npm install && cd ../../..
            - echo "*:*:$PGUSER:$PGPASS:pcorporate" > ~/.pgpass
            - chmod 600 ~/.pgpass
            - psql -h "$PGHOST" -U "$PGUSER" -d pcorporate -t -A -c "select chave_empresa, nome from tb_empresa where status = 0 and chave_empresa <> 'tst' " > empresas.txt
            - git clone "https://$DESIGN_GIT_USER:$DESIGN_GIT_PASS@bitbucket.org/getit-team/pocket-corporate-design" /tmp/pocket-corporate-design
            - mvn clean package
            - cp -R src/main/webapp src/main/webapp-origin
            - awk -F'|' '{system("sh build_deploy.sh \"" $1 "\" \"" $2 "\"")}' empresas.txt
    hml-*:
      - step:
          script:
            - apt-get update
            - apt-get install -y sshpass npm && ln -s /usr/bin/nodejs /usr/bin/node
            - npm install --global bower grunt
            - cd src/main/webapp && npm install && cd ../../..
            - git clone "https://$DESIGN_GIT_USER:$DESIGN_GIT_PASS@bitbucket.org/getit-team/pocket-corporate-design" /tmp/pocket-corporate-design
            - cp -Rf /tmp/pocket-corporate-design/tst/admin/* src/main/webapp/
            - sh build_deploy.sh tst Pocket\ Corporate