image: gafsel/java-postgres-build

pipelines:
  tags:
    prod-*:
      - step:
          script:
            - apt-get update
            - apt-get install -y sshpass npm && ln -s /usr/bin/nodejs /usr/bin/node
            - npm install --global bower@1.6.5 grunt@1.2.0
            - cd src/main/webapp && npm install && cd ../../..
            - echo "*:*:$PGUSER:$PGPASS:calvinista" > ~/.pgpass
            - chmod 600 ~/.pgpass
            - psql -h "$PGHOST" -U "$PGUSER" -d calvinista -t -A -c "select chave_igreja, nome from tb_igreja where status = 0 and chave_igreja <> 'tst' " > igrejas.txt
            - git clone "https://$DESIGN_GIT_USER:$DESIGN_GIT_PASS@bitbucket.org/getit-team/calvinista-design" /tmp/calvinista-design
            - mvn clean package
            - cp -R src/main/webapp src/main/webapp-origin
            - awk -F'|' '{system("sh build_deploy.sh \"" $1 "\" \"" $2 "\"")}' igrejas.txt
    hml-*:
      - step:
          script:
            - apt-get update
            - apt-get install -y sshpass npm && ln -s /usr/bin/nodejs /usr/bin/node
            - npm install --global bower grunt
            - cd src/main/webapp && npm install && cd ../../..
            - git clone "https://$DESIGN_GIT_USER:$DESIGN_GIT_PASS@bitbucket.org/getit-team/calvinista-design" /tmp/calvinista-design
            - cp -Rf /tmp/calvinista-design/tst/admin/* src/main/webapp/
            - sh build_deploy.sh tst Pocket\ Church