image: gafsel/java-postgres-build

pipelines:
  tags:
    prod-*:
      - step:
          script:
            - apt-get update
            - apt-get install -y sshpass && apt-get install -y npm && ln -s /usr/bin/nodejs /usr/bin/node
            - npm install --global bower
            - npm install grunt
            - echo "*:*:$PGUSER:$PGPASS:calvinista" > ~/.pgpass
            - chmod 600 ~/.pgpass
            - psql -h "$PGHOST" -U "$PGUSER" -d calvinista -t -A -c "select chave_igreja, nome from tb_igreja where status = 0 and chave_igreja <> 'tst' " > igrejas.txt
            - git clone "https://$DESIGN_GIT_USER:$DESIGN_GIT_PASS@bitbucket.org/getit-team/calvinista-design" /tmp/calvinista-design
            - echo '#!/bin/bash\n' > /tmp/deploy.sh
            - echo 'cp -Rf /tmp/calvinista-design/$1/admin/* src/main/webapp/' >> /tmp/deploy.sh
            - echo 'mvn clean install -Pprod -Dchave.igreja=$1 -Dnome.igreja="$2" || exit 1\n' >> /tmp/deploy.sh
            - echo 'sshpass -p "$DEPLOY_PASS" scp -o StrictHostKeyChecking=no "target/$1.war" "$DEPLOY_USER@$DEPLOY_HOST:/tmp/" || exit 1\n' >> /tmp/deploy.sh
            - echo 'sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "/opt/glassfish4/glassfish/bin/asadmin undeploy $1 || echo 'Não implantado'" || echo "$1 não estava em execução" \n' >> /tmp/deploy.sh
            - echo 'sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "/opt/glassfish4/glassfish/bin/asadmin deploy /tmp/$1.war || exit 1" \n' >> /tmp/deploy.sh
            - chmod 777 /tmp/deploy.sh
            - awk -F'|' '{system("sh /tmp/deploy.sh \"" $1 "\" \"" $2 "\"")}' igrejas.txt
    hml-*:
      - step:
          script:
            - apt-get update
            - apt-get install -y sshpass && apt-get install -y npm && ln -s /usr/bin/nodejs /usr/bin/node
            - npm install --global bower
            - npm install grunt
            - git clone "https://$DESIGN_GIT_USER:$DESIGN_GIT_PASS@bitbucket.org/getit-team/calvinista-design" /tmp/calvinista-design
            - cp -Rf /tmp/calvinista-design/tst/admin/* src/main/webapp/
            - mvn clean install -Pprod -Dchave.igreja=tst -Dnome.igreja='Pocket Church'
            - sshpass -p "$DEPLOY_PASS" scp -o StrictHostKeyChecking=no target/tst.war "$DEPLOY_USER@$DEPLOY_HOST:/tmp/"
            - sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" '/opt/glassfish4/glassfish/bin/asadmin undeploy tst' || echo "$1 não estava em execução"
            - sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" '/opt/glassfish4/glassfish/bin/asadmin deploy /tmp/tst.war'